services:
  db:
    build:
      context: .
    ports:
      - "5430:5432"
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_data/pg:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  
  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
volumes:
  db_data: