[project]
name = "roprop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.18.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]

[dependency-groups]
dev = [
    "basedpyright>=1.31.6",
    "pytest>=8.4.2"
]
