name: ci
on:
  push:
    branches-ignore:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run ruff
        run: uv run ruff check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@b716db5b717cb9b81e391fe638e5aceaa2299e43 # v2.4.0
        with:
          compose-file: "./compose.yaml"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run pytest
        run: uv run pytest

  dblint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@b716db5b717cb9b81e391fe638e5aceaa2299e43 # v2.4.0
        with:
          compose-file: "./compose.yaml"

      - name: Run dblinter
        run: |
          docker run --rm --network host decathlon/dblinter:latest \
            --dbname postgres \
            --host localhost \
            --user postgres \
            --password postgres \
            --port 5430

  hadolint:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Check if Dockerfile changed
        id: dockerfile_check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^Dockerfile$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - uses: hadolint/hadolint-action@v3.3.0
        if: steps.dockerfile_check.outputs.changed == 'true'
        with:
          dockerfile: Dockerfile